# Generated by Django 5.1.1 on 2024-11-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection(title)
            VALUES ('collection1')             
                          ""","""
            DELETE FROM store_collection
            WHERE title='collection1'
            """)
    ]
