# Generated by Django 5.1.1 on 2024-11-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20241126_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collections',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='describtion',
            new_name='description',
        ),
    ]
